#!/bin/bash
rm -f "/mnt/c/Users/umada/AppData/Local/plover/plover/mejiro.py"
rm -f "/mnt/c/Users/umada/AppData/Local/plover/plover/mejiro_commands.json"
cp -f "./Mejiro_One_Hand/system.py" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/system.py"
cp -f "./Mejiro_One_Hand/dictionaries/default/mejiro_commands.json" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/dictionaries/default/"
cp -f "./Mejiro_One_Hand/dictionaries/default/abbreviations.py" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/dictionaries/default/"
cp -f "./Mejiro_One_Hand/dictionaries/default/func.py" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/dictionaries/default/"
cp -f "./Mejiro_One_Hand/dictionaries/default/mejiro.py" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/dictionaries/default/"
cp -f "./Mejiro_One_Hand/dictionaries/default/settings.py" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/dictionaries/default/"
cp -f "./Mejiro_One_Hand/dictionaries/default/translate.py" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/dictionaries/default/"
cp -f "./Mejiro_One_Hand/dictionaries/default/verb.py" "/mnt/c/Users/umada/AppData/Local/plover/plover/plugins/win/Python313/site-packages/Mejiro_One_Hand/dictionaries/default/"
